### ISSUE TITLE
Project / repo renamed

### ISSUE THREAD

**Issue by Tigge** [Tigge/antfs-cli#122]
@mgr01 @Toilal @christofferholmstedt @lamby @mart-e @codingtony @caius @tfheen I've just renamed the repository here on GitHub to reflect the name change that was done a while back. There should be no immediate effect since GitHub happily uses the old name/repo as an alias to the new one. Feel free to update your remote repos and such if you like. Also, a big thanks for all your help, thoughts and patches!

**Comment by Toilal** [comment]
:+1: Really better :)

**Comment by Toilal** [comment]
You will also need to update README for badges URLs

**Comment by Tigge** [comment]
@Toilal Done!

**Comment by Tigge** [comment]
Also, I force pushed the `split` branch to `master`. So `master` is now the main branch (and the only branch since I deleted the other ones).

**Comment by Tigge** [comment]
Closing this since it is already done, feel free to continue to comment.

**Comment by mgr01** [comment]
:+1: thanks for the info :)
