### ISSUE TITLE
Installation command don't work

### ISSUE THREAD

**Issue by antoniovj1** [Tigge/antfs-cli#125]
sudo setup.py install does not install antfs-cli ( may be a problem in my computer) but I think that the proper command is sudo python setup.py install

**Comment by philipwhiuk** [comment]
It's missing
```
#!/bin/python
```

at the top of the file.

**Comment by Tigge** [comment]
Yeah, the instructions here do say to use `sudo python setup.py install` but adding a shebang would be nice.
