### ISSUE TITLE
-

### ISSUE THREAD

**Issue by antspants** [Tigge/antfs-cli#135]

**Comment by Tigge** [comment]
I guess this solved itself, or (closing, but feel free to reopen)? Was there anything that was unclear that could be improved in the documentation or the program itself?

**Comment by antspants** [comment]
Hi, sorry about that. I couldn't find a way to delete the issue. It turned out that the files are stored under /root/.config which although I'm running the command as sudo, is strange. Considering I get a ~/.config/antfs-cli directory with log files.

For the udev rules, is it enough to just copy resources/ant-usb-sticks.rules file if I installed via pacman? Is there any other magic involved?

Thanks for the library, much appreciated.

-ants

**Comment by Tigge** [comment]
No problem at all, you can just close the issue. Running as root should not be necessary when the udev rules are correctly installed. The setup script should have installed them for you. It installs the openant library which has these rules. For openant it essentially it just runs:
- cp resources/ant-usb-sticks.rules /etc/udev/rules.d
- udevadm control --reload-rules
- udevadm trigger --subsystem-match=usb --attr-match=idVendor=0fcf --action=add

The same code is used for path stuff for logging and for other files, so it should be the same. Weird.

**Comment by antspants** [comment]
Okay, that's all working now. I deleeted most things and redid and it looks good.

Again, thanks for this.

**Comment by Tigge** [comment]
Excellent. And thank you. Let me know if you run into any more trouble.
