### ISSUE TITLE
Track upload to FR 310XT?

### ISSUE THREAD

**Issue by akemper** [Tigge/antfs-cli#139]
I'm about to switch from ForeRunner 205 to 310XT, since the old device is broken. One of the most important functions for me is the option to (still) upload routes to the device, which at least still should be supported by the 310XT. Do antfs-cli / openant support this option as well (probably by "--upload") or are there at least any existing resources which could help me to extend the scripts accordingly?

Thx,
Andreas

**Comment by Tigge** [comment]
You should be able to upload routes using antfs-cli but it has not been tested that much at all. The main issue is that the routes need to be in the FIT format, which can be a bit tricky since I don't think there are that many tools that support it.

How do you do this currently for the 205?

**Comment by akemper** [comment]
FR 205 / 305 have an USB-interface integrated in their cradle, which is used for both charging and sync. This can be easily done for instance with gpsbabel.
Most likely I will get the 310XT and give you an update about the possibilities to upload routes via ANT. From what I've read so far at least some Garmin devices can internally convert route files after placing them in the upload directory (if existing).

**Comment by Tigge** [comment]
I'd be surprised if this functionality was inside the watch firmware. The official Garmin ANT Agent might have done this on the computer side, but I don't think it can happen on the watch itself.

I haven't found any software that converts to the FIT format. The specification are more or less open so it shouldn't be that hard to do for someone with programming experience (and feel comfortable with the licence agreement). See http://www.thisisant.com/resources/fit for more information.

**Comment by embear** [comment]
I'm a Linux only user and am very happy to have antfs-cli to download my activities from my Garmin 310XT. Yesterday I finally managed to download workouts and courses as FIT files from Garmin Connect and send them to my 310XT using antfs-cli. I used the information available [here](https://forums.garmin.com/showthread.php?36791-Course-export&p=627276#post627276) and [here](http://sergeykrasnov.ru/subsites/dev/garmin-connect-statisics/).

I created two bookmarks in Mozilla, one for downloading courses, one for downloading workouts.

```
javascript:(function(){window.location='https://connect.garmin.com/proxy/course-service-1.0/fit'+window.location.pathname.replace("/modern","");})()
```
```
javascript:(function(){window.location='https://connect.garmin.com/proxy/workout-service-1.0/fit'+window.location.pathname.replace("/modern","");})()
```

Now open the course/workout on Garmin Connect site in Mozilla and click on the corresponding bookmark. The script will take the currently opened URL, generate an URL for the Garmin Connect Web API and download the FIT file. After download just put the files to the antfs-cli data folder and run `antfs-cli --upload`.

Hope this helps....

**Comment by Tigge** [comment]
Very nice @embear! I've just enabled a wiki for this project, feel free to add this information there if you like.

**Comment by embear** [comment]
I just created this [wiki page](https://github.com/Tigge/antfs-cli/wiki/HowToDownloadFit). As I am not a native speaker feel free to correct my bad english,

**Comment by akemper** [comment]
Thanks for your interesting work @embear! I'm also a Linux-only user and in addition I don't want to switch to / use the Garmin Connect page.  I find the options to create and review routes there rather limited. Thus I decided to program my own CSV2FIT-converter in CPP, based on the FIT SDK (http://www.thisisant.com/resources/fit). It allows me to take a CSV-file containing WGS-84 coordinates (for example from www.gpsies.com) and convert these to a FIT course-file. So far I've tested it only with my FR 910XT, but pretty sure it should work also with similar devices. When time permits I will  create a public repo for the code.

**Comment by Tigge** [comment]
@embear thank you, looks really good!

**Comment by Tigge** [comment]
@akemper cool, could be a viable alternative. Please update here once you upload the code.

**Comment by akemper** [comment]
Here we go: https://github.com/akemper/CSV2FIT

Please feel free to comment, reuse or even extend the code.
