### ISSUE TITLE
Can not pair my 310XT

### ISSUE THREAD

**Issue by mihaj** [Tigge/antfs-cli#141]
Hi.

I am trying this tool on my Garmin 310XT (latest firmware).

I get stuck here:

```
Driver available: [<class ant.base.driver.SerialDriver at 0x7f06036298d8>, <class ant.base.driver.USB2Driver at 0x7f0603629f58>, <class ant.base.driver.USB3Driver at 0x7f06033db050>]
 - Using: ant.base.driver.SerialDriver
Serial information:
name:             /dev/ttyUSB1
port:             /dev/ttyUSB1
baudrate:         115200
bytesize:         8
parity:           N
stopbits:         1
timeout:          None
writeTimeout:     None
xonxoff:          False
rtscts:           False
dsrdtr:           False
interCharTimeout: None
Request basic information...
  Capabilities:  array('B', [4, 3, 0, 3])
Starting system...
Key done...
Searching...
Authenticating with Forerunner 310XT (3861681798)
 - Pairing: 
```

I don't get any pair prompt on my device. I have data transfer and pairing turned on on the garmin.

What can I do, any ideas?

**Comment by Tigge** [comment]
It looks like it is using the SerialDriver, which is not that functional at the moment. That probably means you have an older USB1-Wireless USB Stick. I know it is not a good solution, but it is possible to buy the newer one from Garmin or other manufacturer. Issue #47 is the main bug for this. Someone had success using a Suunto Movestick Mini in #92 as well.
