### ISSUE TITLE
Upload to Garmin Connect ends with an error message

### ISSUE THREAD

**Issue by michaelwingender** [Tigge/antfs-cli#143]
Hi,
for some time no the upload to Garmin Connect exits with message "gupload.py exited with error code 1". However the fit file is uploading fine and the activity is visible within Garmin connect. Maybe somebody can fix.

Br

**Comment by Tigge** [comment]
Unfortunately I don't have any idea how Garmin Connect works together with antfs-cli. Perhaps @codingtony knows something more?

**Comment by codingtony** [comment]
Hi,

I have the same issue, but I did not look if there is an update on gupload.py

Have you tried :

```
sudo pip install GcpUploader --upgrade
```

Let us know if it fixes the upload.

**Comment by michaelwingender** [comment]
OK. I'm sorry. I think it was wrong to open the issue here. Found the the issue is know for the Uploaeder.
I found a workaround which kind of fixes the issues:
http://sourceforge.net/p/gcpuploader/discussion/general/thread/51de38db/#767a

**Comment by Tigge** [comment]
No problem at all. Good to hear you found a solution. And thanks @codingtony!
