### ISSUE TITLE
unable to install 'package directory 'antfs_cli' does not exist"

### ISSUE THREAD

**Issue by pschriver** [Tigge/antfs-cli#151]
I'm trying to do a new install but keep getting thi error

running install
running bdist_egg
running egg_info
writing requirements to antfs_cli.egg-info/requires.txt
writing antfs_cli.egg-info/PKG-INFO
writing top-level names to antfs_cli.egg-info/top_level.txt
writing dependency_links to antfs_cli.egg-info/dependency_links.txt
writing entry points to antfs_cli.egg-info/entry_points.txt
warning: manifest_maker: standard file 'setup.py' not found

error: package directory 'antfs_cli' does not exist

**Comment by Tigge** [comment]
Hmm, how are you doing this install? What command are you running?

**Comment by pschriver** [comment]
Thanks for the response. I finally was able to get it to work.
