### ISSUE TITLE
Downloaded files nowhere to be found

### ISSUE THREAD

**Issue by tsoenen** [Tigge/antfs-cli#152]
Hi!

Thx for making this application! 

The application ends successfully on my laptop, but I can't find the downloaded files. According to the readme, they should be in the ~/.config/antfs-cli/ directory, but this directory does not exist. There are also no logs in the antfs-cli directory.

Am I doing something wrong, or is there something I'm missing? When I try to download the files again, they seem to be marked as 'already downloaded', as the application quits immediately.

Thx!

**Comment by Tigge** [comment]
You night have another path set for `$XDG_CONFIG_HOME`. It looks for this env var first and then in `~/.config`. Could this be it?

**Comment by tsoenen** [comment]
Ok, found it! I was looking at ./config on my root, not on the HOME directory:)

thx!

**Comment by Tigge** [comment]
Glad you found 'em!
