### ISSUE TITLE
Upload support directly in antfs-cli

### ISSUE THREAD

**Issue by La0** [Tigge/antfs-cli#154]
Hello @Tigge and antfs-cli maintainers,

I have made a [Pull Request on GcpUploader](https://github.com/dlotton/GcpUploader/pull/3), but the owner does not respond to any requests or pings.
I can make another pull request to add Garmin upload capabilities directly into antfs-cli: what is your stand on this ? Would you support such a PR ?

I saw that you use a plugin system to use GCPuploader and parse its output.
The upload feature could be set as an extra in the antfs-cli package (so a user would have to do a pip install antfs-cli[upload] to install requests & the upload code)

Thanks for reading me, antfs-cli is a great tool ;)

**Comment by Tigge** [comment]
I'd definitely not be opposed to adding that to antfs-cli, especially if it can just be hooked into the existing plugin system (not opppsed to modifications to it either, or if you have other ideas). I don't really know how extras work but I'll look into it.

**Comment by La0** [comment]
The developper of GcpUploader reached out to me, i may get contributor access to its repository.
If i can update the project, i would clean its codebase, and write a stable documented api so other projects (such as antfs-cli) can rely on it. 
The integration in antfs-cli would still be a plugin, but using directly a Python api, resulting in a more portable code...

**Comment by La0** [comment]
Hello @Tigge,

I hope you had a great Christmas with your family and friends!
I just published my fork of [GCPUploader](https://github.com/La0/garmin-uploader/), with a cleaner api and unit tests.
Next step is the Pull request to use this in antfs-cli as a plugin :smile:

**Comment by Tigge** [comment]
@La0 nice! I'll take a look at the PR when it is done :).

**Comment by Echelon9** [comment]
Interesting @La0

**Comment by La0** [comment]
I published my [PR on antfs-cli](https://github.com/Tigge/antfs-cli/pull/158), to use garmin-uploader as a plugin. 
As the code does not need any subprocess call anymore, it could be better integrated into antfs-cli main program (as an option)
