### ISSUE TITLE
upload to strava

### ISSUE THREAD

**Issue by mscansian** [Tigge/antfs-cli#171]
Is there any plans to add a feature to upload files to Strava?

**Comment by jklaise** [comment]
You can link a Garmin account to Strava, so anything uploaded to Garmin will automatically be transferred to Strava also.

**Comment by Tigge** [comment]
There are no plans from my side, but this is a good fit for the `scripts` folder where we can take in uploading to other services and other fun bits. A pull requesr would certainly be welcomed! :)
