### ISSUE TITLE
Refresh Strava OAuth token before uploading

### ISSUE THREAD

**Issue by pwithnall** [Tigge/antfs-cli#178]
Currently the Strava upload script seems to assume it has a ‘forever’ OAuth token from Strava, but Strava’s now migrated away from that. OAuth tokens expire after 6 hours, and you need to do a `POST` request to refresh them, using a refresh code provided in response to the initial auth request.

https://developers.strava.com/docs/authentication/#refresh-expired-access-tokens

It would be good if `40-upload_to_strava.py` supported that, since it currently fails all uploads done more than 6 hours after the previous one.

**Comment by mscansian** [comment]
Hi, I submitted a patch that should fix this. It just runs the auth flow if your token is logged of. I understand that this may be a bit annoying, but it's the easiest I could do to get it working.

I'm starting to use Strava again after almost a year and if I see that this is too much of a hassle I will probably think on a better solution.

**Comment by Tigge** [comment]
Should be fixed in #180.
