### ISSUE TITLE
Error running antfs-cli - array index out of range.

### ISSUE THREAD

**Issue by Spinnekop** [Tigge/antfs-cli#187]
Just installed latest openant and antfs-cli on archlinux. Using the ant stick that came with a Gramin FR60. 
This is the error I get as soon as I issue the antfs-cli command. 

Any help appreciated.

[paul@pandawebb antfs-cli-master]$ antfs-cli
Driver available: [<class 'ant.base.driver.USB2Driver'>, <class 'ant.base.driver.USB3Driver'>]
 - Using: <class 'ant.base.driver.USB2Driver'>
Request basic information...
  Capabilities:  array('B', [8, 3, 0, 186, 54, 0])
Starting system...
Key done...
Searching...
Traceback (most recent call last):
  File "/home/paul/antfs-cli-master/antfs_cli/program.py", line 384, in main
    g.start()
  File "/usr/lib/python3.8/site-packages/ant/fs/manager.py", line 223, in start
    self._main()
  File "/usr/lib/python3.8/site-packages/ant/fs/manager.py", line 150, in _main
    if self.on_link(beacon):
  File "/home/paul/antfs-cli-master/antfs_cli/program.py", line 167, in on_link
    self.link()
  File "/usr/lib/python3.8/site-packages/ant/fs/manager.py", line 383, in link
    self._send_command(LinkCommand(self._frequency, 4, self._serial_number))
  File "/usr/lib/python3.8/site-packages/ant/fs/manager.py", line 199, in _send_command
    self._channel.send_acknowledged_data(data)
  File "/usr/lib/python3.8/site-packages/ant/easy/channel.py", line 119, in send_acknowledged_data
    self.wait_for_event([Message.Code.EVENT_TRANSFER_TX_COMPLETED])
  File "/usr/lib/python3.8/site-packages/ant/easy/channel.py", line 50, in wait_for_event
    return wait_for_event(ok_codes, self._node._events, self._node._event_cond)
  File "/usr/lib/python3.8/site-packages/ant/easy/filter.py", line 73, in wait_for_event
    return wait_for_message(match, process, queue, condition)
  File "/usr/lib/python3.8/site-packages/ant/easy/filter.py", line 45, in wait_for_message
    if match(message):
  File "/usr/lib/python3.8/site-packages/ant/easy/filter.py", line 68, in match
    return data[0] in ok_codes
IndexError: array index out of range
Interrupted: array index out of range
[paul@pandawebb antfs-cli-master]$

**Comment by Tigge** [comment]
Yeah I'm getting the same thing. Investigating.

**Comment by Tigge** [comment]
Should be fixed in openant now. Please try updating openant (or reinstall) and try again.

**Comment by Spinnekop** [comment]
Hi Gustav - working great now - still love my old FR60&70. This is probably due to the watch but any idea why the files would have dates of 1989, 1990 & 1991? When I uploaded to garmin it gave the correct date of the activity. However, when I synced with strava it gave the 1991 date. I got round it by exporting the tcx file and doing a find and replace and then uploading again but it was a bit of a pain. 
Here is the start of a tcx file. The ID date is correct but all of the other dates and time are wrong. 
Any idea? 

<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase
  xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd"
  xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1"
  xmlns:ns3="http://www.garmin.com/xmlschemas/ActivityExtension/v2"
  xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2"
  xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1">
  <Activities>
    <Activity Sport="Running">
      <Id>2020-11-25T13:40:00.000Z</Id>
      <Lap StartTime="1991-12-26T01:25:15.000Z">
        <TotalTimeSeconds>320.0</TotalTimeSeconds>
        <DistanceMeters>1000.0</DistanceMeters>
        <MaximumSpeed>3.26200008392334</MaximumSpeed>
        <Calories>82</Calories>
        <Intensity>Active</Intensity>
        <TriggerMethod>Manual</TriggerMethod>
        <Track>
          <Trackpoint>
            <Time>1991-12-26T01:25:16.000Z</Time>
            <DistanceMeters>0.0</DistanceMeters>
            <Extensions>
              <ns3:TPX>
                <ns3:Speed>0.0</ns3:Speed>
              </ns3:TPX>
            </Extensions>
          </Trackpoint>

**Comment by Spinnekop** [comment]
Thanks - all good now!!
