### ISSUE TITLE
Success with FR70 (as root). Possible udev rules issue?

### ISSUE THREAD

**Issue by dje7** [Tigge/antfs-cli#49]
Success with Garmin FR70 (as root).

I have a Garmin FR70 with a USB2 ANT stick
$  lsusb | grep -i dyna*
Bus 003 Device 002: ID 0fcf:1008 Dynastream Innovations, Inc.

I have a rule in the rules.d folder that says:
KERNEL=="3-1", ATTR{idVendor}=="0fcf", ATTR{idProduct}=="1008", SYMLINK+="ttyUSB0", MODE="0660", ACTION=="add"

This resulted in successful pairing with the watch using garmin-ant-downloader, but it gets me a file ".gant" that I don't know what to do with and I could not get FIT files. After installing Garmin-Forerunner-610-Extractor:

If I do not run as root:
daniel@daniel-1000H ~/garmin/Garmin-Forerunner-610-Extractor $ python garmin.py
Traceback (most recent call last):
  File "garmin.py", line 205, in main
    g = Garmin()
  File "garmin.py", line 56, in **init**
    Application.**init**(self)
  File "/home/daniel/garmin/Garmin-Forerunner-610-Extractor/ant/fs/manager.py", line 64, in **init**
    self._node = Node(0x0fcf, 0x1008)
  File "/home/daniel/garmin/Garmin-Forerunner-610-Extractor/ant/easy/node.py", line 48, in __init__
    self.ant = Ant(idVendor, idProduct)
  File "/home/daniel/garmin/Garmin-Forerunner-610-Extractor/ant/base/ant.py", line 52, in **init**
    for cfg in dev:
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/core.py", line 733, in **iter**
    yield Configuration(self, i)
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/core.py", line 419, in **init**
    configuration
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/backend/libusb1.py", line 471, in get_configuration_descriptor
    config, byref(cfg)))
  File "/usr/local/lib/python2.7/dist-packages/pyusb-1.0.0a3-py2.7.egg/usb/backend/libusb1.py", line 403, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
USBError: [Errno 5] Input/output error
Interrupted
Traceback (most recent call last):
  File "garmin.py", line 214, in <module>
    sys.exit(main())
  File "garmin.py", line 210, in main
    g.stop()
UnboundLocalError: local variable 'g' referenced before assignment

If I run as root:
daniel@daniel-1000H ~/garmin/Garmin-Forerunner-610-Extractor $ sudo python garmin.py
Request basic information...
  ANT version:   AJK1.04RAF
  Capabilities:  array('B', [8, 3, 0, 186, 54, 0])
  Serial number: 2956597
Starting system...
Searching...
Authenticating with FR70 (1259281)
- Pairing: OK
  Downloading 8 file(s)
  Downloading 1990-01-01_02-36-43-80-280.fit [..........]
  Downloading 1990-01-01_02-15-40-80-499.fit [..........]
  Downloading 1990-01-02_03-52-10-80-499.fit [..........]
  Downloading 1989-12-30_20-37-29-80-499.fit [..........]
  Downloading 1989-12-30_18-43-35-80-168.fit [..........]
  Downloading 1990-01-01_03-14-16-80-138.fit [..........]
  Downloading 1989-12-30_20-03-32-80-3439.fit [..........]
  Downloading 1990-01-01_03-14-16-80-3576.fit [..........]

**Comment by krissen** [comment]
Hi. Also having the problem of only being able to run as root (FR610). Doubt it would be udev rules at fault, because I've successfully been using a previous version. Switched from garmin.py to anfs-cli, and now have to access as root.

(Also, can't find the udev rules "shipped with this application". Stored where?)

**Comment by Tigge** [comment]
The udev rules are part of the https://github.com/Tigge/openant project nowadays. Root should not be needed. What USB stick are you using? Are the udev rules installed in `/etc/udev/rules.d/`?

**Comment by krissen** [comment]
*Sigh.* Must be I'm imagining things. It's working now. As normal user. I get this can't be the case, but seems to me that once it had worked as root, it also started working as normal user. I'm just going to leave it be (as long as it's working) and not think anymore on this. Sorry for taking your time.

**Comment by Tigge** [comment]
At least it works :smile:
