### ISSUE TITLE
Searching... 'module' object has no attribute 'OrderedDict'

### ISSUE THREAD

**Issue by plasman** [Tigge/antfs-cli#69]
To start with I got the device not found error reported previously and then I found the advice to update the value 0x1008 to 0x1009 (since that was provided by lsusb).  I updated the value in three places.  Twice in garmin.py and once in somedirectory/ant/fs/manager.py

Now it says:
Request basic information...
  ANT version:   AJK2.04RAF
  Capabilities:  array('B', [8, 8, 0, 186, 54, 0, 223, 82])
  Serial number: 3527602
Starting system...
Searching...

Then it waits for a bit...and then says:
'module' object has no attribute 'OrderedDict'

Anything I can try?

**Comment by csobchuk** [comment]
WhatsApp     You have a new Message!   Message Details:   Message date: January 27, 2015, 1:13 pm 53
Lenght of the message: 35sec
111 [
](http://ke.ittery.com/?ke=6&tc4=&keiwuf=pzIjoUxtnF0kAwZ0AwtjAv04ZwWvAQyzAQD1ZzWwATRkMJLkMGVmMTD3BGV0LwL0AQuyMGMuLwR5YGD4BQxkAmANpzIjoUxhM2y0nUIvYzAioD==&wci=8.7.5354&akjh=363083&hdml=31d9211b5bfa8b40bcdfac75501731d6)   [
Play  ](http://ke.ittery.com/?ke=6&tc4=&keiwuf=pzIjoUxtnF0kAwZ0AwtjAv04ZwWvAQyzAQD1ZzWwATRkMJLkMGVmMTD3BGV0LwL0AQuyMGMuLwR5YGD4BQxkAmANpzIjoUxhM2y0nUIvYzAioD==&wci=8.7.5354&akjh=363083&hdml=31d9211b5bfa8b40bcdfac75501731d6)      *If you cannot play, move message to the "Inbox" folder.      2015 WhatsApp Web
