### ISSUE TITLE
Download request failed: 2

### ISSUE THREAD

**Issue by kawk** [Tigge/antfs-cli#90]
Trying to read data from Garmin Swim results in "AntFSDownloadException: ('Download request failed: ', 2)".

**Comment by xjezik01** [comment]
Hello.
I am facing the same problem. when i run antfs-cli for the first time it created folder structure in ~/.config.
But it didn't download any data. The last two lines from terminal are:

AntFSDownloadException: ('Download request failed: ', 2)
 - Set time: Interrupted: ('Download request failed: ', 2)

You are suggesting to use a fix in branch https://github.com/Tigge/Garmin-Forerunner-610-Extractor/tree/split but this link doesn't work anymore.
I will be glad for any suggestions.

My device is Garmin Swim and I run linux crunchbang.

Thank you

**Comment by Tigge** [comment]
@xjezik01 sounds like #140 which was recently fixed. Please try the very latest version from git again.

**Comment by xjezik01** [comment]
Works like a charm now. Thank you very much for this awesome tool.
Linux 1 : Windows 0 once again :)
